"""FalconAI_Clothe_Service URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin


from crawler import views
from rest_framework.schemas import get_schema_view
from rest_framework_swagger.views import get_swagger_view
from django.conf.urls import include, url


schema_view = get_swagger_view(title='FalconAI Clothe Service')

urlpatterns = [
    url('^$', schema_view),
    url(r'^admin/', admin.site.urls),
    # url(r'^clotheImagesView/', views.ClotheImagesView.as_view()),
    # url(r'^clotheImagesInferredView/', views.ClotheImagesInferredView.as_view()),
    # url(r'^clotheImagesInferredView/', views.ClotheImagesView.as_view()),
    # url(r'^api/clothes/(?P<clotheId>[0-9]+)$', views.ClotheImagesView.as_view()),
    url(r'^api/PostClotheImagesView/', views.PostClotheImagesView.as_view()),
    url(r'^api/GetAllClotheImagesView/', views.GetAllClotheImagesView.as_view()),



    # root view of our REST api, generated by Django REST Framework's router
]
